### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by soywiz** [romhackhispano/aegis.romhackhispano.org#1]
Si quieres montar un blog o un cms similar a lo que tienes de tumblr, github soporta [jekyll](https://jekyllrb.com/) directamente.
Igual ya lo sabías pero yo te lo comento.
El blog de tales-tra lo moví a jekyll ayer con muy buenos resultados, y también pude migrar todos los comentarios de wordpress a disqus muy fácilmente.
Lo bueno de jekyll es que no tiene base de datos y de que github pregenera las páginas en cada commit.

https://github.com/talestra/blog.tales-tra.com
http://blog.tales-tra.com/

Ejemplo de post (se puede markdown y html):
https://github.com/talestra/blog.tales-tra.com/blob/gh-pages/_posts/2016-07-30-rescatando-el-blog.md
https://raw.githubusercontent.com/talestra/blog.tales-tra.com/gh-pages/_posts/2016-07-30-rescatando-el-blog.md

Si te gusta la idea, pero no te aclaras, te puedo ayudar con ello.

Saludos

**Comment by TheFireRed** [comment]
Sí, ¡de hecho estaba ya trasteando con Jekyll! Estoy configurando el ordenador para trabajar con él. ¡Gracias!

**Comment by TheFireRed** [comment]
Bien, creo que he dejado los dominios como debería. Supongo que primero tendré que esperar a que se actualicen las DNS. Lo único que he visto raro antes es que la página no renderizaba bien; es como si se hubiese perdido el CSS. Esperaré unas horas.

**Comment by soywiz** [comment]
Guay. No, lo que pasa es que el archivo dns.txt, es simplemente de referencia. Tengo que copiarlo y pegarlo en el gestor de dominios para actualizarlo. (Lo acabo de hacer). No sé si tendrán API para hacerlo automático, pero la desconozco. Así que de momento está en modo manual :) Avísame si de aquí a 10 minutos (tras hacer flush de las dns) te sigue sin salir.

Saludos.
