### ISSUE TITLE
Listar noticias de cada proyecto

### ISSUE THREAD

**Issue by TheFireRed** [romhackhispano/aegis.romhackhispano.org#2]
Ahora mismo tengo [dos ](https://github.com/romhackhispano/aegis.romhackhispano.org/blob/gh-pages/_posts/2015-02-13-zelda-101.md) [artículos](https://github.com/romhackhispano/aegis.romhackhispano.org/blob/gh-pages/_posts/2015-02-13-zelda-101.md) de prueba con el tag `The Legend of Zelda` y categoría `Traducciones`. Quiero mostrar en las páginas con el layout `tradu` una lista de noticias relevantes a cada proyecto, como aparecen en Tales-Tra, con el tag `project_tag` (de hecho, [esta parte del código](https://github.com/romhackhispano/aegis.romhackhispano.org/blob/gh-pages/_layouts/tradu.html#L26) es la misma). Entiendo que el código dice que si el tag de los posts es equivalente a project_tag, debe mostrar los enlaces. Sin embargo, en la página **The Legend of Zelda** no aparece la lista. ¿Qué me falta, o qué es lo que falla?

¡Un saludo y gracias!

**Comment by soywiz** [comment]
```
project_tag: [The Legend of Zelda]
```
->
```
project_tag: "The Legend of Zelda"
```

**Comment by TheFireRed** [comment]
Perfecto, qué error más tonto. ¡Muchas gracias!

**Comment by soywiz** [comment]
Por cierto. Igual te interesa saber:

Documentación de liquid: https://shopify.github.io/liquid/
Y luego de jekyll: https://jekyllrb.com/docs/templates/

Si en algún punto te encuentras con la limitación de no poder poner expresiones arbitrarias:
{% assign variable = expression %}

Y luego hay un filtro"where", que puedes usar junto a assign, para hacer algo tipo:

```
{% assign posts2 = site.posts|when "key", "value" %}
{% if posts2 %}
<h2>Noticias</h2>
{% for post2 in posts2 %}
...
{% endfor %}
{% endif %}
```

En jekyll 3.2 hay un where_exp, que es más flexible y permitirá por ejemplo usar el operador "contains", o usar rangos.

Actualmente github soporta la 3.1, pero imagino que en algún punto la soportarán.

Aquí sale la versión de jekyll y los plugins soportados actualmente por github: https://pages.github.com/versions/

**Comment by TheFireRed** [comment]
¡Gracias! Hora de empaparme con esto de Liquid.

**Comment by TheFireRed** [comment]
¡A buenas horas! Ahora que estaba contento con el diseño que había elegido y modificado a mi gusto. :laughing:

**Comment by soywiz** [comment]
No pasa nada, lo puedes dejar tal cual :), pero podrás usar las cosas nuevas como el where_exp
