### ISSUE TITLE
Page build failure genérico

### ISSUE THREAD

**Issue by TheFireRed** [romhackhispano/aegis.romhackhispano.org#5]
He intentado buscar qué es lo que me da error y no lo encuentro. Cualquier cosa que subo, por sencilla que sea, me da page build failure sin ninguna explicación más... ¿qué estoy haciendo mal?

Simplemente he subido una noticia con imágenes y no genera la página. Como no he encontrado nada, he revertido los cambios hasta la última actualización correcta... ¡y aun así da page build failure!

**Comment by soywiz** [comment]
A ver si es que al actualizar a jekyll 3.2 se ha roto por algún motivo. ¿Has probado a bajarte jekyll 3.2 en tu ordenador y ver si chuta ahí?

**Comment by TheFireRed** [comment]
Eso he pensado. Quizá el tema no es totalmente compatible con la versión y se ha ido todo al garete. Mañana pruebo a trastear en local.

**Comment by TheFireRed** [comment]
Sí, definitivamente era culpa del tema. Lo han actualizado para que la configuración no se solape. https://github.com/rohanchandra/type-theme/commit/6eebbf5b86e1183a10ce9e37e11a717161fc1e0b

**Comment by TheFireRed** [comment]
Ya parece que funciona. ¡Gracias!
